[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    '@paima/evm-contracts/=node_modules/@paima/evm-contracts/',
    'erc721a/=node_modules/erc721a/'

]
solc_version = '0.8.23'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
